// <auto-generated/>
#pragma warning disable CS1591
namespace ImageViewer.Views;

using Avalonia.Controls;

public partial class FolderPreviewView : UserControl
{
    public FolderPreviewView()
    {
        InitializeComponent();
    }
}