// <auto-generated/>
#pragma warning disable CS1591
namespace ImageViewer.Views;

using Avalonia.Controls;

public partial class FolderListView : UserControl
{
    public FolderListView()
    {
        InitializeComponent();
    }
}