// <auto-generated/>
#pragma warning disable CS1591
using Avalonia.Controls;
using ImageViewer.ViewModels;

namespace ImageViewer.Views;

public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        DataContext = new MainWindowViewModel(this);
    }
}