// <auto-generated/>
#pragma warning disable CS1591
using Avalonia.Controls;

namespace ImageViewer.Views;

public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
    }
}